spring:
  config:
    import: optional:dotenv:.env
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/jagalchi_node?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul}
    username: ${SPRING_DATASOURCE_USERNAME:jagalchi}
    password: ${SPRING_DATASOURCE_PASSWORD:jagalchi123}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST:jagalchi-redis}
      port: ${REDIS_PORT:6379}

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    gajeman.jagalchi: INFO
